version: "3.9"

services:

  # ───────── AUTH DATABASE ─────────
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - auth_data:/var/lib/postgresql/data
    networks:
      - taskboard-net

  # ───────── TASK DATABASE ─────────
  task-db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./task-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - task_data:/var/lib/postgresql/data
    networks:
      - taskboard-net

  # ───────── USER DATABASE ─────────
  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./user-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - user_data:/var/lib/postgresql/data
    networks:
      - taskboard-net


  # ───────── AUTH SERVICE ─────────
  auth-service:
    build: ./auth-service
    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_NAME: authdb
      DB_USER: admin
      DB_PASSWORD: secret
      JWT_SECRET: mysecretkey
      JWT_EXPIRES: 1h
      PORT: 3001
    depends_on:
      - auth-db
    networks:
      - taskboard-net
    restart: unless-stopped


  # ───────── TASK SERVICE ─────────
  task-service:
    build: ./task-service
    environment:
      DB_HOST: task-db
      DB_PORT: 5432
      DB_NAME: taskdb
      DB_USER: admin
      DB_PASSWORD: secret
      JWT_SECRET: mysecretkey
      AUTH_SERVICE_URL: http://auth-service:3001
      PORT: 3002
    depends_on:
      - task-db
      - auth-service
    networks:
      - taskboard-net
    restart: unless-stopped


  # ───────── USER SERVICE ─────────
  user-service:
    build: ./user-service
    environment:
      DB_HOST: user-db
      DB_PORT: 5432
      DB_NAME: userdb
      DB_USER: admin
      DB_PASSWORD: secret
      JWT_SECRET: mysecretkey
      AUTH_SERVICE_URL: http://auth-service:3001
      PORT: 3004
    depends_on:
      - user-db
      - auth-service
    networks:
      - taskboard-net
    restart: unless-stopped


  # ───────── FRONTEND ─────────
  frontend:
    build: ./frontend
    networks:
      - taskboard-net


  # ───────── NGINX (API Gateway + TLS) ─────────
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - auth-service
      - task-service
      - user-service
      - frontend
    networks:
      - taskboard-net
    restart: unless-stopped


volumes:
  auth_data:
  task_data:
  user_data:


networks:
  taskboard-net:
    driver: bridge